# Generated by Django 3.1.4 on 2021-01-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210125_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='year',
        ),
    ]
