# Generated by Django 3.1.4 on 2021-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_books_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date',
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.DateField(default=0),
        ),
    ]
