# Generated by Django 3.1.4 on 2021-01-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210127_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='genge',
            new_name='genre',
        ),
    ]
