# Generated by Django 3.1.4 on 2021-01-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_books_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
    ]
