# Generated by Django 3.1.4 on 2021-01-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_books_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='year',
        ),
    ]
