# Generated by Django 3.1.4 on 2021-01-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_books_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
